### ISSUE TITLE
board

### ISSUE THREAD

**Issue by ghost** [nesshy9/sleepchan#1]
your demo just goes to the default ubuntu page. also, i would highly recommend sqlite3 db over your flatfile system. If you want a flatfile type no mysql system, with php - sqlite3 db is the way to go. The sqlite3 db is just a flat file that is on your system- nothing to configure. Also as a fyi- ChatGPT can crank out a far superior board that looks exactly like yours, and do it in one single php file.  You do not have to wait for ppl to help you with it as you mentioned, just use chatgpt to write your code for you.

**Comment by tomoko-dev9** [comment]
> your demo just goes to the default ubuntu page. also, i would highly recommend sqlite3 db over your flatfile system. If you want a flatfile type no mysql system, with php - sqlite3 db is the way to go. The sqlite3 db is just a flat file that is on your system- nothing to configure. Also as a fyi- ChatGPT can crank out a far superior board that looks exactly like yours, and do it in one single php file. You do not have to wait for ppl to help you with it as you mentioned, just use chatgpt to write your code for you.

thank you as for the demo i am gonna use a different domain

**Comment by ghost** [comment]
i just made a repo called php, each folder is a different php ib that chatgpt made or edited. enjoy.

**Comment by ghost** [comment]
![Screenshot 2024-11-30 082545](https://github.com/user-attachments/assets/d2e198d5-3dad-449b-ae95-f0873af87717)

tested in php 8.4.1 (the very latest version) the images and css do not show up. You have a nice board, i see the general idea. json flatfiles can be efficient for very small apps, but do not scale well. 

Overall, you have a nice app but it could use some changes. First, you have lots of files and a large codebase, it is actually very possible to put all your code into 1 or 2 php files, and the files would not even be that big. If you have access to chatgpt (openai. org) it is about 22 usd a month, you could make any php app of your dreams with it. It writes the code for you. It will explain that postgres, mongo, mysql is best, then sqlite3 then any flatfile like json flatfiles, csv or whatever are okay but do not scale well. You can sit there and have an hour long conversation about what db to use and chatgpt will give you very good advice and teach you things. look at my archived /php repo, it has some very simple and small php apps that do what yours does- but mine are in one small php file. The code was all made with way older versions of chatgpt, but it serves as a demo. You see, chat gpt never makes perfect code right away, it makes code, you run it, and tell it what changes you want or feed it the error messages the server returns, after a few edits by chatgpt you will have the php app of your dreams.

**Comment by ghost** [comment]
please see my demo at https://github.com/x1a7x/ib     each folder is its own app. it is ONE small php file for each app! It actually makes the db for you if its not there. Just an example of what you can instantly make with chatgpt.

**Comment by ghost** [comment]
im not sure if you have access to chatgpt or not, or want to stick to json flatfiles no matter what. If you get stuck or want me to have chatgpt make an app for you, just create an issue in my /phpib repo !! Ive had chatgpt make lots of json flatfile apps for me in the past. The idea of flatfile is nice, but flatfiles are limited, to be sure.

**Comment by tomoko-dev9** [comment]
> please see my demo at https://github.com/x1a7x/ib each folder is its own app. it is ONE small php file for each app! It actually makes the db for you if its not there. Just an example of what you can instantly make with chatgpt.

i like it looks really good

**Comment by tomoko-dev9** [comment]
i like the css also

**Comment by ghost** [comment]
css can make it look like anything. i just use the older look css to dev the app, when and if the app is perfect and all the details worked out, then as the last step one can make the css look any way needed. the main point of the demo is to show that one can just put it all in one simple php file. With PHP, less is often more!

**Comment by ghost** [comment]
https://4chess.com/2/  here is a demo of my latest phpib version. it has a reply area, and when a reply is made to any post it makes the post go to the top on the main board like regular imageboards do. feel free to test it if you want. you can have all the code if you want to use it... after all i did not make it, chat gpt did. Oah it has a mod area too at mod.php. the password to get into the mod area is mod123 in case you want to see what the mod area looks like. I will leave it up for a day or 2. Its safe, it does not store ip or anything.

**Comment by x1a7x** [comment]
here is another. i made the most simple ib possible, one php file and one css file. it has some decent security features. https://github.com/x1a7x/simple-ib

**Comment by tomoko-dev9** [comment]
> here is another. i made the most simple ib possible, one php file and one css file. it has some decent security features. https://github.com/x1a7x/simple-ib

whats the best way to contact you do you have discord?

**Comment by x1a7x** [comment]
i will have a site in a while, i havent worked with php in ages, just getting something going for now. if you want code or an app made i could help (for free of course) just make an issue in one of my repos, write here or go to my current demo https://4chess.com/2/ and write something. https://4chess.com/ib6/ here is the newest app im working on it looks nice and does images or mp4 upload, i think it might be the best. If you write on one of my demo sites just let me know via github so i can check it. I just started yesterday, ill make a permanent demo after i figure out what apps i want to work on more.

**Comment by x1a7x** [comment]
or if you are looking for an ib, there is vichan, lynxchan, jschan, tinyib they are all the most popular ones, all easy to install if you have hosting. if you only want to do json flatfile to make it work on any shared host i can have chat gpt make an app too. like i say i just got back into it yesterday, so if you want help with code or advice just ask. I like the idea of imageboards (as long as they are not used for crazy purposes) and always help ppl who want to work on sites.

**Comment by x1a7x** [comment]
update... https://4chess.com/ib6/  will be off and on, it has a couple bugs i am trying to have chatgpt fix. it is not currently working, probably will be up and running in a few min tho

**Comment by x1a7x** [comment]
I am focusing on dev of https://github.com/x1a7x/Claire for a php ib. There is a demo link on top of the readme, all the older links i posted earlier might not work because im focusing on claire dev and re-organizing everything.
