### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by ghost** [nesshy9/sleepchan#2]
did you ever get this board working? i had ai put it all into one file and it still does not work on php 8.4.1 - i think there are some compatibility issues with php 8.4.1   the reason i asked is i dont think this works. If you want, explain in detail how you want the board to be, what version of php you want to code it in and i can have chatgpt make the board for you.  if ur bored sometime check out https://github.com/x1a7x/Adelia its the best php  ib i ever made so far.

**Comment by x1a7x** [comment]
the reason i asked is i dont think this works. If you want, explain in detail how you want the board to be, what version of php you want to code it in and i can have chatgpt make the board for you.
